services:
  app:
    image: ghcr.io/amrkmn/pta:latest
    container_name: pta
    ports:
      - 3930:3930
    environment:
      PORT: 3930
      DATABASE_URL: postgresql://postgres:password@db:5432/pta
      JWT_SECRET: 
      S3_ENDPOINT: 
      S3_PORT: 
      S3_USE_SSL: 
      S3_ACCESS_KEY_ID: 
      S3_SECRET_ACCESS_KEY: 
      S3_HOST: ''
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: pta-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: